### ISSUE TITLE
README points to old repo

### ISSUE THREAD

**Issue by guettli** [mikekeda/django-debug-toolbar-line-profiler#4]
The README points to https://github.com/rkern/line_profiler

But this repo is archived. AFAIK the new link is this: https://github.com/pyutils/line_profiler

**Comment by Mogost** [comment]
I'm pretty sure the author of this fork (@mikekeda) is open to accept pull requests.

**Comment by mikekeda** [comment]
Merged PR and released new version 0.7.2
Sorry for the delay
