### ISSUE TITLE
How to install this fork?

### ISSUE THREAD

**Issue by guettli** [mikekeda/django-debug-toolbar-line-profiler#5]
How to install this fork, since `pip install django-debug-toolbar-line-profiler` will install the old version (pre fork) from the year 2016.

**Comment by guettli** [comment]
It worked like this:

```
pip install -e git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler
```

Maybe the old author will give you the permission for pypi, to make this fork "official"?

**Comment by Mogost** [comment]
@guettli `pip install django-debug-toolbar-line-profiling` will install this fork

I tried several times to get in touch with the original author, but to no avail.

**Comment by dedanirungu** [comment]
I am getting the following error.

`pip install -e git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler
Obtaining django-debug-toolbar-line-profiler from git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler
  Updating /var/www/html/python/virtualenvs/src/django-debug-toolbar-line-profiler clone
  Running command git fetch -q --tags
  Running command git reset --hard -q ab16f86277fcac7719b4e216db5dc13e325e7f55
  WARNING: Generating metadata for package django-debug-toolbar-line-profiler produced metadata for project name django-debug-toolbar-line-profiling. Fix your #egg=django-debug-toolbar-line-profiler fragments.
WARNING: Discarding git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler. Requested django-debug-toolbar-line-profiling from git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler has inconsistent name: filename has 'django-debug-toolbar-line-profiler', but metadata has 'django-debug-toolbar-line-profiling'
ERROR: Could not find a version that satisfies the requirement django-debug-toolbar-line-profiler (unavailable) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.6.1)
ERROR: No matching distribution found for django-debug-toolbar-line-profiler (unavailable)
`

**Comment by dedanirungu** [comment]
I am getting the following error.

`pip install -e git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler
Obtaining django-debug-toolbar-line-profiler from git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler
  Updating /var/www/html/python/virtualenvs/mybizna/src/django-debug-toolbar-line-profiler clone
  Running command git fetch -q --tags
  Running command git reset --hard -q ab16f86277fcac7719b4e216db5dc13e325e7f55
  WARNING: Generating metadata for package django-debug-toolbar-line-profiler produced metadata for project name django-debug-toolbar-line-profiling. Fix your #egg=django-debug-toolbar-line-profiler fragments.
WARNING: Discarding git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler. Requested django-debug-toolbar-line-profiling from git+https://github.com/mikekeda/django-debug-toolbar-line-profiler.git#egg=django-debug-toolbar-line-profiler has inconsistent name: filename has 'django-debug-toolbar-line-profiler', but metadata has 'django-debug-toolbar-line-profiling'
ERROR: Could not find a version that satisfies the requirement django-debug-toolbar-line-profiler (unavailable) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.6.1)
ERROR: No matching distribution found for django-debug-toolbar-line-profiler (unavailable)
`
